In [66]:
import pandas as pd
import numpy as np

In [67]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [68]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [69]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [72]:
X_falso = np.arange(10)
X_falso

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
np.random.seed(0)
train_test_split(X_falso, test_size=0.5)

[array([6, 7, 3, 0, 5]), array([2, 8, 4, 9, 1])]

In [78]:
modelo = RandomForestClassifier(n_estimators=100, n_jobs=-1, random_state=0)


In [79]:
def transformar_sexo(valor):
    if valor == 'female':
        return 1
    else:
        return 0
    
train['Sex_binario'] = train['Sex'].map(transformar_sexo)

In [80]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Sex_binario  
0      0         A/5 21171   7.2500   NaN        S            0  
1      0          PC 17599  71.2833   C85        C            1  
2      0  STON/O2. 3101282   7.9250   NaN        S            1  
3      0            113803  53.1000  C123        S            1  
4      0            373450   8.0500   NaN        S            0

In [81]:
variaveis = ['Sex_binario', 'Age']

In [82]:
X = train[variaveis]
y = train['Survived']

In [83]:
X.head()

Sex_binario   Age
0            0  22.0
1            1  38.0
2            1  26.0
3            1  35.0
4            0  35.0

In [84]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [85]:
 X =  X.fillna(-1)

In [86]:
modelo.fit(X,y)

RandomForestClassifier(n_jobs=-1, random_state=0)

In [87]:
test['Sex_binario'] = test['Sex'].map(transformar_sexo)

In [88]:
X_prev = test[variaveis]
X_prev = X_prev.fillna(-1)
X_prev.head()

Sex_binario   Age
0            0  34.5
1            1  47.0
2            0  62.0
3            0  27.0
4            1  22.0

In [89]:
p = modelo.predict(X_prev)
p

array([0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [90]:
test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  Sex_binario  
0  34.5      0      0   330911   7.8292   NaN        Q            0  
1  47.0      1      0   363272   7.0000   NaN        S            1  
2  62.0      0      0   240276   9.6875   NaN        Q            0  
3  27.0      0      0   315154   8.6625   NaN        S            0  
4  22.0      1      1  3101298  12.2875   NaN        S            1

In [91]:
sub = pd.Series(p, index=test['PassengerId'], name = 'Survived')
sub.shape

(418,)

In [92]:
sub.to_csv('primeiro_modelo.csv', header = True)

In [93]:
df_check = pd.read_csv('primeiro_modelo.csv')
df_check.head(10)

PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         1
4          896         1
5          897         0
6          898         1
7          899         0
8          900         1
9          901         0

#atentar

In [94]:
np.random.seed(0)
X_treino, X_valid, y_treino, y_valid = train_test_split(X, y, test_size=0.5)

In [95]:
np.random.seed(0)
X_treino, X_valid, y_treino, y_valid = train_test_split(X, y, test_size=0.5)

In [96]:
X_treino.head()

Sex_binario   Age
213            0  30.0
586            0  47.0
499            0  24.0
821            0  27.0
246            1  25.0

In [97]:
X_treino.shape, X_valid.shape, y_treino.shape, y_valid.shape

((445, 2), (446, 2), (445,), (446,))

In [98]:
modelo = RandomForestClassifier(n_estimators=100, n_jobs=-1, random_state=0)

modelo.fit(X_treino, y_treino)

RandomForestClassifier(n_jobs=-1, random_state=0)

In [99]:
p = modelo.predict(X_valid)

In [100]:
np.mean(y_valid == p)

0.7690582959641256

In [101]:
p = (X_valid['Sex_binario'] == 1).astype(np.int64)
np.mean(y_valid == p)

0.7825112107623319

##Validação cruzada

In [102]:
X_falso

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
from sklearn.model_selection import KFold

In [105]:
kf = KFold(3, shuffle=True, random_state=0)
for linhas_treino, linhas_valid in kf.split(X_falso):
    print("Treino:", linhas_treino)
    print("Valid",  linhas_valid)
    print()

Treino: [0 1 3 5 6 7]
Valid [2 4 8 9]

Treino: [0 2 3 4 5 8 9]
Valid [1 6 7]

Treino: [1 2 4 6 7 8 9]
Valid [0 3 5]



In [116]:


resultados = []
for rep in range(10):
    print("Rep:", rep)
    kf = KFold(2, shuffle=True, random_state=rep)

    for linhas_treino, linhas_valid in kf.split(X):
        print("Treino:", linhas_treino.shape[0])
        print("Valid",  linhas_valid.shape[0])
        print()
        
        X_treino, X_valid = X.iloc[linhas_treino],  X.iloc[linhas_valid]
        y_treino, y_valid = y.iloc[linhas_treino],  y.iloc[linhas_valid]

        #print(X_treino.head())
        #print()
        modelo = RandomForestClassifier(n_estimators=100, n_jobs=-1, random_state=0)
        modelo.fit(X_treino, y_treino)
        
        p = modelo.predict(X_valid)
        
        acc = np.mean(y_valid == p)
        resultados.append(acc)
        print("Acc:", acc)
    


Rep: 0
Treino: 445
Valid 446

Acc: 0.7713004484304933
Treino: 446
Valid 445

Acc: 0.7797752808988764
Rep: 1
Treino: 445
Valid 446

Acc: 0.7443946188340808
Treino: 446
Valid 445

Acc: 0.7955056179775281
Rep: 2
Treino: 445
Valid 446

Acc: 0.7757847533632287
Treino: 446
Valid 445

Acc: 0.7887640449438202
Rep: 3
Treino: 445
Valid 446

Acc: 0.7533632286995515
Treino: 446
Valid 445

Acc: 0.7573033707865169
Rep: 4
Treino: 445
Valid 446

Acc: 0.7354260089686099
Treino: 446
Valid 445

Acc: 0.7415730337078652
Rep: 5
Treino: 445
Valid 446

Acc: 0.7219730941704036
Treino: 446
Valid 445

Acc: 0.7056179775280899
Rep: 6
Treino: 445
Valid 446

Acc: 0.7757847533632287
Treino: 446
Valid 445

Acc: 0.7303370786516854
Rep: 7
Treino: 445
Valid 446

Acc: 0.7040358744394619
Treino: 446
Valid 445

Acc: 0.7348314606741573
Rep: 8
Treino: 445
Valid 446

Acc: 0.7488789237668162
Treino: 446
Valid 445

Acc: 0.7887640449438202
Rep: 9
Treino: 445
Valid 446

Acc: 0.7623318385650224
Treino: 446
Valid 445

Acc: 0.7842696

In [117]:
resultados

[0.7713004484304933,
 0.7797752808988764,
 0.7443946188340808,
 0.7955056179775281,
 0.7757847533632287,
 0.7887640449438202,
 0.7533632286995515,
 0.7573033707865169,
 0.7354260089686099,
 0.7415730337078652,
 0.7219730941704036,
 0.7056179775280899,
 0.7757847533632287,
 0.7303370786516854,
 0.7040358744394619,
 0.7348314606741573,
 0.7488789237668162,
 0.7887640449438202,
 0.7623318385650224,
 0.7842696629213484]

In [118]:
np.mean(resultados)

0.7550007557817302